addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
    - beineri/opt-qt55
    packages:
    - ubuntu-sdk
    - libboost-all-dev
    - qt55-meta
    - gcc-5

language: cpp
sudo: false
cache:
    apt: true
    ccache: true
    directories:
        ~/deps
        ~/repos

compiler:
  - clang
  - g++

before_install:
  - $TRAVIS_BUILD_DIR/before_install.sh

before_script:
  - ls ~/deps
  - ls ~/repos
  - cd $TRAVIS_BUILD_DIR
  - ls

script:
  - $TRAVIS_BUILD_DIR/script.sh