language: cpp
sudo: required
compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-add-repository -y ppa:kubuntu-ci/stable-daily
  - sudo apt-get update -qqy

install:
  - sudo apt-get install -qqy qtcreator qtcreator-dev

script:
  - qmake ./BALLS/BALLS.pro
  - make