addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
    packages:
    - libboost-dev
    - gcc-5
    - clang-3.7
    - llvm-3.7

language: cpp
sudo: required
services:
    - docker
cache:
    apt: true
    ccache: true
    directories:
        ~/deps
        ~/repos

compiler:
  - clang
  - g++

before_install:
  - mkdir -p ~/repos
  - sudo add-apt-repository -y 'deb http://ppa.launchpad.net/beineri/opt-qt55-trusty/ubuntu trusty main'
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.7 main'
  - sudo apt-get -qqy update
  - sudo apt-get install --no-install-recommends --force-yes --no-upgrade -qqy qt553d qt55base qt55-meta-full
  - sudo chmod -f +x /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qt55-env.sh
  - $TRAVIS_BUILD_DIR/before_install.sh

install:
  - $TRAVIS_BUILD_DIR/install.sh

before_script:
  - cd $TRAVIS_BUILD_DIR

script:
  - $TRAVIS_BUILD_DIR/script.sh