addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
    packages:
    - ubuntu-sdk
    - libboost-all-dev

language: cpp
sudo: false
cache:
    apt: true
    ccache: true
    directories:
        ~/deps
        ~/repos

compiler:
  - clang
  - g++

before_install:
  - $TRAVIS_BUILD_DIR/before_install.sh

before_script:
  - ls ~/deps
  - ls ~/repos
  - cd $TRAVIS_BUILD_DIR
  - ls

script:
  - qmake ./BALLS/BALLS.pro -r -spec linux-$CC
  - make