addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
    packages:
    - qtcreator
    - qtcreator-dev

language: cpp
sudo: false
cache:
    apt: true
    ccache: true
    directories:
        deps

compiler:
  - clang
  - g++

before_install:
  - echo $LANG
  - echo $LC_ALL

script:
  - qmake ./BALLS/BALLS.pro
  - make