language: cpp
sudo: required
compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install ubuntu-sdk

script:
  - qmake ./BALLS/BALLS.pro
  - make

os:
  - linux
  - osx