addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
    packages:
    - qtcreator
    - qtcreator-dev

language: cpp
sudo: false
cache:
    apt: true
    ccache: true
    directories:
        deps
        repos

compiler:
  - clang
  - g++

before_install:
  - 'mkdir -p ~/repos'
  - cd ~/repos
  - "[[ ! -e glm ]] && git clone https://github.com/g-truc/glm.git"
  - cd ./glm
  - '[[ ! -e CMakeCache.txt ]] && cmake -DCMAKE_INSTALL_PREFIX:FILEPATH="~/deps"'

before_script:
  - cd $TRAVIS_BUILD_DIR
  - ls

script:
  - qmake ./BALLS/BALLS.pro
  - make