addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
    packages:
    - qtcreator
    - qtcreator-dev

language: cpp
sudo: false
cache:
    apt: true
    ccache: true
    directories:
        deps
        repos

compiler:
  - clang
  - g++

before_install:
  - cd ./repos
  - ls
  - git clone https://github.com/g-truc/glm.git
  - cd ./glm
  - cmake -DCMAKE_INSTALL_PREFIX:FILEPATH="~/deps"

script:
  - qmake ./BALLS/BALLS.pro
  - make