language: cpp
sudo: required
compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qqy

install:
  - sudo apt-get install -qqy ubuntu-sdk qtcreator qtcreator-dev
  - ls -w 80 -R /usr/include/qt5

script:
  - qmake ./BALLS/BALLS.pro
  - make

os:
  - linux
  - osx