addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team

language: cpp
sudo: required
services:
    - docker
cache:
    apt: true
    ccache: true
    directories:
        ~/deps
        ~/repos

compiler:
  - clang
  - g++

before_install:
  - $TRAVIS_BUILD_DIR/before_install.sh

install:
  - $TRAVIS_BUILD_DIR/install.sh
  - update-alternatives --get-selections

before_script:
  - cd $TRAVIS_BUILD_DIR

script:
  - $TRAVIS_BUILD_DIR/script.sh